apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: products-ms
  name: products-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: products-ms
    spec:
      containers:
        - image: southamerica-east1-docker.pkg.dev/nest-microservices-427320/image-registry/products-ms
          name: products-ms
          env:
            - name: PORT
              value: "8081"
            - name: DATABASE_URL
              value: "file:./dev.db"
            - name: NATS_SERVERS
              value: "nats://nats"
          resources: {}
status: {}
