services:
  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"

  # CLIENT-GATEWAY
  client-gateway:
    build: ./client-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: pnpm start:dev
    environment:
      - PORT=8080
      - NATS_SERVERS=nats://nats-server:4222

  # PRODUCTS-MS
  product-ms:
    build: ./products
    volumes:
      - ./products/src:/usr/src/app/src
    command: pnpm start:dev
    environment:
      - PORT=8081
      - DATABASE_URL=file:./dev.db
      - NATS_SERVERS=nats://nats-server:4222

  # ORDERS-DB
  orders-db:
    container_name: orders_database
    image: postgres:16.2
    # volumes:
    #   - ./orders/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=orders

  # ORDERS-MS
  orders-ms:
    depends_on:
      - orders-db
    build: ./orders
    volumes:
      - ./orders/src:/usr/src/app/src
    command: pnpm start:dev
    environment:
      - PORT=8082
      - DATABASE_URL=postgresql://postgres:123456@orders-db/orders?schema=public
      - NATS_SERVERS=nats://nats-server:4222

  # PAYMENTS-MS
  payments-ms:
    build: ./payments
    volumes:
      - ./payments/src:/usr/src/app/src
    command: pnpm start:dev
    environment:
      - PORT=8083
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - SUCCES_URL=${SUCCES_URL}
      - CANCEL_URL=${CANCEL_URL}

  #AUTH-MS
  auth-ms:
    build: ./auth
    volumes:
      - ./auth/src:/usr/src/app/src
    command: pnpm start:dev
    environment:
      - PORT=8084
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${AUTH_JWT_SECRET}
