apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
        - image: southamerica-east1-docker.pkg.dev/nest-microservices-427320/image-registry/payments-ms
          name: payments-ms
          env:
            - name: PORT
              value: "8083"
            - name: NATS_SERVERS
              value: "nats://nats"
            - name: STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: stripe_secret
            - name: STRIPE_ENDPOINT_SECRET
              valueFrom:
                secretKeyRef:
                  name: payments-secrets
                  key: stripe_endpoint_secret
            - name: SUCCES_URL
              value: "http://localhost:8083/payments/success"
            - name: CANCEL_URL
              value: "http://localhost:8083/payments/cancel"
          resources: {}
status: {}
