apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: payments-webhook
  name: payments-webhook
spec:
  ports:
    - name: "8083"
      port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app: payments-ms
  type: NodePort
status:
  loadBalancer: {}
